修复两个玩家同时发射火箭复制物品的bug
SlimefunGuguProject/Galactifun pull request #30
Opened 2024-01-08 04:48 UTC by ExpertSneeker

## Changes
当玩家输入坐标时将火箭的状态设置为发射中，进入输入坐标状态前检测是否处于发射中，如果发射中则无法进入输入状态。

## Related Issues
Syntax: "利用火箭刷物品 #29"

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break world generation, mob spawning, and the like.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values

2024-04-05 06:28 UTC, ybw0014 requested changes

2024-04-05 06:28 UTC, ybw0014 commented on src/main/java/io/github/addoncommunity/galactifun/base/BaseItems.java
> -                BaseMats.ALUMINUM_COMPOSITE_SHEET, SlimefunItems.BLOCK_PLACER, BaseMats.ALUMINUM_COMPOSITE_SHEET
撤销该更改。修改配方可通过附属SlimeFunRecipe。

2024-06-07 14:13 UTC, ybw0014 commented
建议单独开个分支用于PR

2024-06-07 18:14 UTC, ExpertSneeker commented
> 建议单独开个分支用于PR

成，没用过这功能搞不明白

2024-06-07 19:03 UTC, closed without merging